<a href="https://colab.research.google.com/github/arunabiz/numpy_exercises/blob/main/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [63]:
import time

**1. How to create a list in Python?**

In [6]:
a = [1,2,3,4]
b = list([1,2,3,4])
a==b

True

**2. What is the difference between a list and an array in Python?**

Lists can contain diferrent data types of elements while an array can only contain the same data type of elements

An array is the best for numarical calculations and can be converted into a Numpy array.

**3. How to convert a list into a numpy array?**

In [10]:
c = np.array([1,2,3,4])
type(c)

numpy.ndarray

**4. How to perform arithmetic operations on numpy arrays?**

In [11]:
d = c+1
print(d)

[2 3 4 5]


**5. How to calculate the mean, median, and standard deviation of a numpy array?**

In [18]:
mean = np.mean(c)
print("Mean:", mean)

median = np.median(c)
print("Median:", median)

std = np.std(c)
print("Standard Deviation:", std)

Mean: 2.5
Median: 2.5
Standard Deviation: 1.118033988749895


**6. How to perform matrix operations in numpy, such as transpose, dot product, and inverse?**

In [24]:
d = np.array([[1,2,3,4],[5,6,7,8]])
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
transpose = d.T
print(transpose)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [32]:
e = np.array([[1,2],[3,4],[5,6],[7,8]])
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
dot_product = np.dot(d, e)
print(dot_product)


[[ 50  60]
 [114 140]]


In [45]:
f = np.array([[1, 2], [3, 4]])
print(f)
inv = np.linalg.inv(f)
print(inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


**7. How to select elements from a numpy array based on conditions?**

In [49]:
indices = np.where(e > 5)
selected = e[indices]
print(selected)

[6 7 8]


**8. How to perform element-wise operations on numpy arrays?**

In [57]:
g = np.array([1,2,3,4,5,6])
h = np.array([6,7,8,9,3,7])

Add = g+h
print(Add)

Substract = g-h
print(Substract)

[ 7  9 11 13  8 13]
[-5 -5 -5 -5  2 -1]


**9. How to reshape a numpy array?**

In [61]:
i = h.reshape(2,3)
print(i)

[[6 7 8]
 [9 3 7]]


**10. How to measure the time taken by a numpy operation?**

In [64]:
j = np.random.rand(1000,10000)

start = time.time()

result = np.mean(j)

end = time.time()

time_taken = end-start
print("Time:", time_taken)

Time: 0.008107900619506836
